// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public values — safe to commit. The anon/publishable key is designed to be
// exposed to the browser; row-level security protects the data. Hardcoding
// them as fallbacks lets standalone builds (e.g. Hostinger) work without a
// local .env file. Env vars still take precedence when present.
const FALLBACK_SUPABASE_URL = 'https://ppzpihpzmvgqumjvxuvb.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwenBpaHB6bXZncXVtanZ4dXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0NzI4NTksImV4cCI6MjA4NDA0ODg1OX0.oMELHAOPgOVDiFMopdYVBkmcaHvhHYPeDoEQZ8cM5B0';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = true;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});